server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
    min-response-size: 1024
  http2:
    enabled: true

spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://localhost:5432/wcs
    username: wcs
    password: wcs
  jpa:
    properties:
      hibernate:
        defaultSchema: public
        jdbc.lob.non_contextual_creation: true
    hibernate:
      naming:
        physical-strategy: it.bz.opendatahub.webcomponents.common.hibernate.CamelSnakeNamingStrategy

logging:
  file: logs/delivery.log
  level:
    #org.springframework: 'INFO'
    org.slf4j: 'INFO'
    ti.bz.opendatahub.webcomponents: 'INFO'
    liquibase.executor: 'INFO'