server:
  port: 9010

spring:
  application:
    name: crawler-service
  datasource:
    url: jdbc:postgresql://localhost:5432/wcs
    username: wcs
    password: wcs
  jpa:
    properties:
      hibernate:
        defaultSchema: public
        jdbc.lob.non_contextual_creation: true
    hibernate:
      naming:
        physical-strategy: it.bz.opendatahub.webcomponents.common.hibernate.CamelSnakeNamingStrategy

logging:
  file: logs/crawler.log
  level:
    #org.springframework: 'INFO'
    org.slf4j: 'INFO'
    it.bz.opendatahub.webcomponents: 'INFO'
    liquibase.executor: 'INFO'

application:
  workspace:
    path: 'workspace'
  schedule:
    origin: 60000 # 60*1000
    component: 60000 # 60*1000
  repository:
    github:
      token:
    origin:
      url: https://github.com/uhufa/odh-web-components-store-demo-origins.git
      branch: master
