version: "3.4"
services:
  frontend:
    container_name: wcstore_frontend
    build:
      context: ./frontend
      dockerfile: docker/dockerfile-node-local
    volumes:
      - ./frontend/:/code
    working_dir: /code
    env_file: .env
    command: sh -c "test -d node_modules || yarn; yarn dev"
    depends_on:
        - api
        - cdn
    ports:
      - "${FRONTEND_PORT}:3000"
    tty: true

  api:
    container_name: wcstore_api
    build:
      context: backend
      dockerfile: data-service/infrastructure/docker/Dockerfile-local
    volumes:
      - ./workspace:/workspace
    env_file:
      - .env
        
    depends_on:
      - postgres
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    tty: true

  cdn:
    container_name: wcstore_cdn
    build:
      context: backend
      dockerfile: delivery-service/infrastructure/docker/Dockerfile-local
    volumes:
      - ./workspace:/workspace
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${CDN_SERVER_PORT}:${CDN_SERVER_PORT}"
    tty: true

  postgres:
    container_name: wcstore_postgres
    image: postgres:13
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: wcs
      POSTGRES_PASSWORD: wcs
      POSTGRES_DB: wcs

  wcstore-cli:
    container_name: wcstore-cli
    build:
      context: webcompstore-cli
      dockerfile: Dockerfile
    env_file: .env
    command: ./wait-for -t 0 api:5001 -- python webcompstore-cli.py --push ${WC_VERSION}
    depends_on:
      - api
    volumes:
      - ${WC_PATH}:${WC_PATH}
