version: "3.4"

services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    build:
      context: ../..
      dockerfile: infrastructure/docker/java.dockerfile
      target: build
    env_file: 
      - ../../../.env
    volumes:
      - ../../.m2:/code/.m2
