version: "3.4"
services:
  api:
    container_name: wcstore
    build:
      context: ../..
      dockerfile: infrastructure/docker/java.dockerfile
      target: build
    env_file: 
      - .env
    volumes:
      - ../../.m2:/code/.m2
        