version: "3.4"

services:
  crwaler:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}-cdn

    restart: unless-stopped
    env_file: 
      - .env
    environment:
      CDN_SERVER_PORT: ${CDN_SERVER_PORT}
    volumes: 
      - ../shared/workspace:/workspace
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:${CDN_SERVER_PORT}/actuator/health"]
    #   interval: 20s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 30s
    ports:
      - "${CDN_SERVER_PORT}:${CDN_SERVER_PORT}"