name: Build and push dev store docker image

on: 
  push:
  pull_request:

env:
  PROJECT_NAME: odh-webcompstore-dev-docker
  JAVA_VERSION: '8'
  DOCKER_REGISTRY_HOST: ghcr.io

jobs:
  test:
    runs-on: ubuntu-20.04        
    steps:
      - uses: actions/checkout@v2

  deploy-test-data-service:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: test
    concurrency: deploy-test-data-service
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}-wcs-image
      DOCKER_TAG: ${{ github.sha }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Build and push 
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          docker-host: ${{ env.DOCKER_REGISTRY_HOST }}
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./local-wcs

  deploy-prod-data-service:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/prod'
    needs: test
    concurrency: deploy-prod-data-service
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}-wcs-image
      DOCKER_TAG: ${{ github.sha }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Build and push 
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          docker-host: ${{ env.DOCKER_REGISTRY_HOST }}
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./local-wcs