name: CI/CD frontend

on: 
  push:
    paths:
      - 'frontend/**'
      - '!backend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
      - '!backend/**'



jobs:
  test:
    runs-on: ubuntu-20.04        
    steps:
      - uses: actions/checkout@v2
      - name: Test frontend
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - run: |
          yarn install
          yarn run test --passWithNoTests
        working-directory: frontend


  deploy-test-frontend:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs: test
    concurrency: deploy-test-frontend
    env:
      AWS_S3_BUCKET_NAME : 'webcompstore-test'
      AWS_REGION : "eu-west-1"

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        with:
          working-directory: "frontend"
        env:
          X_COMPOSE_PROJECT_NAME: ${{ env.PROJECT_NAME }}

          X_API_BASE_URL: "https://api.webcomponents.opendatahub.testingmachine.eu"
          X_CDN_URL: "https://cdn.webcomponents.opendatahub.testingmachine.eu"
          X_GOOGLE_ANALYTICS_ID: ${{ secrets.WEBCOMPSTORE_TEST_GOOGLE_ANALYTICS_ID }}
          X_GOOGLE_ANALYTICS_DEBUG: false

      - name: run ls to check .env location in .
        run: ls -la

      - name: run ls to check .env location in frontend
        run: ls -la frontend

      - name: Setup node and yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Build 
        run: |
          yarn install
          yarn run build
        working-directory: frontend


      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v2
        with:
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./frontend/dist